# Generated by CodiumAI

from pr_agent.algo.types import FilePatchInfo
from pr_agent.algo.utils import find_line_number_of_relevant_line_in_file


class TestFindLineNumberOfRelevantLineInFile:
    # Returns the correct line number and absolute position when the relevant line is in the patch
    def test_relevant_line_found_in_patch(self):
        diff_files = [
            FilePatchInfo(
                base_file="file1",
                head_file="file1",
                patch="@@ -1,1 +1,2 @@\n-line1\n+line2\n+relevant_line\n",
                filename="file1",
            )
        ]
        relevant_file = 'file1'
        relevant_line_in_file = 'relevant_line'
        expected = (3, 2) # (position in patch, absolute_position in new file)
        assert find_line_number_of_relevant_line_in_file(diff_files, relevant_file, relevant_line_in_file) == expected

    def test_exact_raw_patch_line_skips_difflib(self, monkeypatch):
        diff_files = [
            FilePatchInfo(
                base_file="file1",
                head_file="file1",
                patch="@@ -1 +1 @@\n-old\n+new\n",
                filename="file1",
            )
        ]

        def fail_if_called(*args, **kwargs):
            raise AssertionError("difflib should not run for an exact raw patch-line match")

        monkeypatch.setattr("pr_agent.algo.utils.difflib.get_close_matches", fail_if_called)

        assert find_line_number_of_relevant_line_in_file(
            diff_files, "file1", "+new"
        ) == (2, 1)

    # Returns the correct line number when a similar line is found using difflib
    def test_similar_line_found_using_difflib(self):
        diff_files = [
            FilePatchInfo(
                base_file="file1",
                head_file="file1",
                patch="@@ -1,1 +1,2 @@\n-line1\n+relevant_line in file similar match\n",
                filename="file1",
            )
        ]
        relevant_file = 'file1'
        # trailing space simulates a similar line found using difflib
        relevant_line_in_file = '+relevant_line in file similar match '
        expected = (2, 1)
        assert find_line_number_of_relevant_line_in_file(diff_files, relevant_file, relevant_line_in_file) == expected

    # Returns (-1, -1) when the relevant line is not in the patch and no similar line is found
    def test_relevant_line_not_found(self):
        diff_files = [
            FilePatchInfo(
                base_file="file1",
                head_file="file1",
                patch="@@ -1,1 +1,2 @@\n-line1\n+relevant_line\n",
                filename="file1",
            )
        ]
        relevant_file = 'file1'
        relevant_line_in_file = 'not_found'
        expected = (-1, -1)
        assert find_line_number_of_relevant_line_in_file(diff_files, relevant_file, relevant_line_in_file) == expected

    # Returns (-1, -1) when the relevant file is not found in any of the patches
    def test_relevant_file_not_found(self):
        diff_files = [
            FilePatchInfo(
                base_file="file1",
                head_file="file1",
                patch="@@ -1,1 +1,2 @@\n-line1\n+relevant_line\n",
                filename="file2",
            )
        ]
        relevant_file = 'file1'
        relevant_line_in_file = 'relevant_line'
        expected = (-1, -1)
        assert find_line_number_of_relevant_line_in_file(diff_files, relevant_file, relevant_line_in_file) == expected

    # Returns (-1, -1) when the relevant_line_in_file is an empty string
    def test_empty_relevant_line(self):
        diff_files = [
            FilePatchInfo(
                base_file="file1",
                head_file="file1",
                patch="@@ -1,1 +1,2 @@\n-line1\n+relevant_line\n",
                filename="file1",
            )
        ]
        relevant_file = 'file1'
        relevant_line_in_file = ''
        expected = (-1, -1)
        assert find_line_number_of_relevant_line_in_file(diff_files, relevant_file, relevant_line_in_file) == expected

    # Returns (-1, -1) when the relevant line is found in the patch but deleted
    def test_relevant_line_found_but_deleted(self):
        diff_files = [
            FilePatchInfo(
                base_file="file1",
                head_file="file1",
                patch="@@ -1,2 +1,1 @@\n-line1\n-relevant_line\n",
                filename="file1",
            )
        ]
        relevant_file = 'file1'
        relevant_line_in_file = 'relevant_line'
        expected = (-1, -1)
        assert find_line_number_of_relevant_line_in_file(diff_files, relevant_file, relevant_line_in_file) == expected

    def test_hunk_header_with_omitted_counts(self):
        """Parse a hunk header whose count is omitted, which git writes whenever a side
        spans exactly one line, instead of raising TypeError on int(None)."""
        diff_files = [
            FilePatchInfo(base_file="file1", head_file="file1",
                          patch="@@ -1 +1 @@\n-alpha\n+ALPHA", filename="file1")
        ]

        position, absolute_position = find_line_number_of_relevant_line_in_file(
            diff_files, "file1", "+ALPHA")

        assert position == 2
        assert absolute_position == 1

    def test_hunk_header_with_omitted_count_on_the_new_side_only(self):
        diff_files = [
            FilePatchInfo(base_file="file1", head_file="file1",
                          patch="@@ -0,0 +1 @@\n+only_line", filename="file1")
        ]

        position, absolute_position = find_line_number_of_relevant_line_in_file(
            diff_files, "file1", "+only_line")

        assert position == 1
        assert absolute_position == 1

    def test_combined_diff_header_does_not_crash(self):
        """Skip a combined/merge hunk header (@@@) instead of crashing on its None regex match."""
        diff_files = [
            FilePatchInfo(base_file="file1", head_file="file1",
                          patch="@@@ -1,2 -1,2 +1,4 @@@\n- a\n +b\n  c\n +d", filename="file1")
        ]

        position, absolute_position = find_line_number_of_relevant_line_in_file(
            diff_files, "file1", "c")

        assert position == -1
        assert absolute_position == -1

    def test_combined_diff_header_absolute_position_does_not_crash(self):
        diff_files = [
            FilePatchInfo(base_file="file1", head_file="file1",
                          patch="@@@ -1,2 -1,2 +1,4 @@@\n- a\n +b\n  c\n +d", filename="file1")
        ]

        position, absolute_position = find_line_number_of_relevant_line_in_file(
            diff_files, "file1", "not_found", absolute_position=3)

        assert position == -1

    def test_combined_diff_header_plus_line_does_not_crash(self):
        diff_files = [
            FilePatchInfo(base_file="file1", head_file="file1",
                          patch="@@@ -1,2 -1,2 +1,4 @@@\n- a\n +b\n  c\n +d", filename="file1")
        ]

        position, absolute_position = find_line_number_of_relevant_line_in_file(
            diff_files, "file1", "+b")

        assert position == -1
        assert absolute_position == -1

    def test_a_valid_hunk_after_a_combined_header_is_still_found(self):
        """Keep anchoring from a valid hunk rendered after a skipped combined header."""
        combined = "@@@ -1,2 -1,2 +1,4 @@@\n- a\n +b\n  c\n +d"
        valid_hunk = "@@ -3,1 +5,1 @@\n ctx\n-old\n+new"
        diff_files = [
            FilePatchInfo(base_file="file1", head_file="file1",
                          patch=combined + "\n" + valid_hunk, filename="file1")
        ]

        position, absolute_position = find_line_number_of_relevant_line_in_file(
            diff_files, "file1", "new")

        assert position == 8
        assert absolute_position == 6

    def test_no_newline_marker_does_not_shift_absolute_line_lookup(self):
        patch = (
            "@@ -1 +1 @@\n"
            "-old\n"
            "\\ No newline at end of file\n"
            "+new\n"
            "\\ No newline at end of file\n"
        )
        diff_files = [
            FilePatchInfo(base_file="old", head_file="new", patch=patch, filename="file1")
        ]

        assert find_line_number_of_relevant_line_in_file(
            diff_files, "file1", "", absolute_position=1
        ) == (3, 1)

    def test_no_newline_marker_is_ignored_when_matching_source_lines(self):
        patch = (
            "@@ -1 +1 @@\n"
            "-old\n"
            "\\ No newline at end of file\n"
            "+new\n"
            "\\ No newline at end of file\n"
        )
        diff_files = [
            FilePatchInfo(base_file="old", head_file="new", patch=patch, filename="file1")
        ]

        for relevant_line in ("new", "ne", "+   new"):
            assert find_line_number_of_relevant_line_in_file(
                diff_files, "file1", relevant_line
            ) == (3, 1)

        assert find_line_number_of_relevant_line_in_file(
            diff_files, "file1", "No newline"
        ) == (-1, -1)

    def test_no_newline_marker_does_not_interfere_with_fuzzy_matching(self):
        patch = (
            "@@ -1 +1 @@\n"
            "-old\n"
            "\\ No newline at end of file\n"
            "+No newline at end of file\n"
            "\\ No newline at end of file\n"
        )
        diff_files = [
            FilePatchInfo(base_file="old", head_file="No newline at end of file", patch=patch, filename="file1")
        ]

        assert find_line_number_of_relevant_line_in_file(
            diff_files, "file1", "No newline at end of filee"
        ) == (3, 1)
