from datetime import datetime, timezone
from types import SimpleNamespace
from unittest.mock import MagicMock, call, patch

import pytest

from pr_agent.algo.types import EDIT_TYPE
from pr_agent.algo.utils import PRReviewHeader, PRReviewIdentity
from pr_agent.git_providers.codecommit_provider import CodeCommitFile, CodeCommitProvider, PullRequestCCMimic
from pr_agent.tools.pr_reviewer import PRReviewer


class TestCodeCommitFile:
    # Test that a CodeCommitFile object is created successfully with valid parameters.
    # Generated by CodiumAI
    def test_valid_parameters(self):
        a_path = "path/to/file_a"
        a_blob_id = "12345"
        b_path = "path/to/file_b"
        b_blob_id = "67890"
        edit_type = EDIT_TYPE.ADDED

        file = CodeCommitFile(a_path, a_blob_id, b_path, b_blob_id, edit_type)

        assert file.a_path == a_path
        assert file.a_blob_id == a_blob_id
        assert file.b_path == b_path
        assert file.b_blob_id == b_blob_id
        assert file.edit_type == edit_type
        assert file.filename == b_path


class TestCodeCommitProvider:
    @staticmethod
    def _make_diff_provider(git_files):
        provider = object.__new__(CodeCommitProvider)
        provider.repo_name = "my_test_repo"
        provider.pr = PullRequestCCMimic("Encoding test", [])
        provider.pr.destination_commit = "destination-commit"
        provider.pr.source_commit = "source-commit"
        provider.diff_files = None
        provider.git_files = git_files
        provider.codecommit_client = MagicMock()
        return provider

    @staticmethod
    def _make_persistent_provider(targets=None):
        provider = object.__new__(CodeCommitProvider)
        provider.repo_name = "source-repository"
        provider.pr_num = 321
        provider.pr_url = (
            "https://us-east-1.console.aws.amazon.com/codesuite/codecommit/"
            "repositories/source-repository/pull-requests/321"
        )
        provider.diff_files = None
        provider.git_files = []
        provider.codecommit_client = MagicMock()
        targets = targets or [
            SimpleNamespace(
                repository_name="source-repository",
                source_commit="source-commit-1",
                source_branch="refs/heads/feature",
                destination_commit="destination-commit-1",
                destination_branch="refs/heads/main",
            )
        ]
        provider.pr = PullRequestCCMimic("Persistent PR", [], targets=targets)
        provider.pr.source_commit = targets[0].source_commit
        provider.pr.source_branch = targets[0].source_branch
        provider.pr.destination_commit = targets[0].destination_commit
        provider.pr.destination_branch = targets[0].destination_branch
        return provider

    @staticmethod
    def _comment(
        body,
        comment_id="comment-1",
        created_at=None,
        last_modified_at=None,
        **overrides,
    ):
        comment = {
            "commentId": comment_id,
            "content": body,
            "creationDate": created_at or datetime(2024, 1, 1, tzinfo=timezone.utc),
            "lastModifiedDate": last_modified_at or created_at or datetime(2024, 1, 1, tzinfo=timezone.utc),
            "authorArn": "arn:aws:iam::123456789012:user/pr-agent",
        }
        comment.update(overrides)
        return comment

    @staticmethod
    def _comment_group(
        *comments,
        repository_name="source-repository",
        before_commit_id="old-destination-commit",
        after_commit_id="old-source-commit",
        location=None,
    ):
        group = {
            "repositoryName": repository_name,
            "beforeCommitId": before_commit_id,
            "afterCommitId": after_commit_id,
            "comments": list(comments),
        }
        if location is not None:
            group["location"] = location
        return group

    @staticmethod
    def _successful_update_response(comment_id, body):
        return {"comment": {"commentId": comment_id, "content": body, "deleted": False}}

    def test_get_diff_files_includes_deleted_file(self):
        provider = object.__new__(CodeCommitProvider)
        provider.repo_name = "my_test_repo"
        provider.pr = PullRequestCCMimic("Delete file", [])
        provider.pr.destination_commit = "destination-commit"
        provider.pr.source_commit = "source-commit"
        provider.diff_files = None
        provider.git_files = [
            CodeCommitFile("deleted.py", "before-id", "", "", EDIT_TYPE.DELETED)
        ]
        provider.codecommit_client = MagicMock()
        provider.codecommit_client.get_file.side_effect = lambda _, path, __: b"old contents\n" if path else ""

        diff_files = provider.get_diff_files()

        assert [diff_file.filename for diff_file in diff_files] == ["deleted.py"]
        assert diff_files[0].base_file == "old contents\n"
        assert diff_files[0].head_file == ""
        assert diff_files[0].edit_type == EDIT_TYPE.DELETED
        assert "-old contents" in diff_files[0].patch
        assert provider.codecommit_client.get_file.call_args_list == [
            call("my_test_repo", "deleted.py", "destination-commit")
        ]

    @pytest.mark.parametrize(
        ("non_utf8_file", "invalid_path", "invalid_commit"),
        [
            (CodeCommitFile("", "", "added.py", "after-id", EDIT_TYPE.ADDED), "added.py", "source-commit"),
            (CodeCommitFile("deleted.py", "before-id", "", "", EDIT_TYPE.DELETED), "deleted.py", "destination-commit"),
            (
                CodeCommitFile("modified.py", "before-id", "modified.py", "after-id", EDIT_TYPE.MODIFIED),
                "modified.py",
                "destination-commit",
            ),
            (
                CodeCommitFile("modified.py", "before-id", "modified.py", "after-id", EDIT_TYPE.MODIFIED),
                "modified.py",
                "source-commit",
            ),
            (
                CodeCommitFile("old.py", "before-id", "new.py", "after-id", EDIT_TYPE.RENAMED),
                "old.py",
                "destination-commit",
            ),
        ],
    )
    def test_get_diff_files_skips_non_utf8_file_and_keeps_utf8_sibling(
        self,
        non_utf8_file,
        invalid_path,
        invalid_commit,
    ):
        valid_file = CodeCommitFile("good.py", "before-id", "good.py", "after-id", EDIT_TYPE.MODIFIED)
        provider = self._make_diff_provider([non_utf8_file, valid_file])

        def get_file(_repo_name, path, commit):
            if path == invalid_path and commit == invalid_commit:
                return b"\xffinvalid\n"
            return b"before\n" if commit == "destination-commit" else b"after\n"

        provider.codecommit_client.get_file.side_effect = get_file

        diff_files = provider.get_diff_files()

        assert [diff_file.filename for diff_file in diff_files] == ["good.py"]
        assert diff_files[0].base_file == "before\n"
        assert diff_files[0].head_file == "after\n"
        assert "-before" in diff_files[0].patch
        assert "+after" in diff_files[0].patch
        assert diff_files[0].edit_type == EDIT_TYPE.MODIFIED
        assert provider.diff_files is diff_files

    def test_get_diff_files_filters_invalid_extension_before_fetching_content(self):
        ignored_file = CodeCommitFile("image.png", "before-id", "image.png", "after-id", EDIT_TYPE.MODIFIED)
        valid_file = CodeCommitFile("good.py", "before-id", "good.py", "after-id", EDIT_TYPE.MODIFIED)
        provider = self._make_diff_provider([ignored_file, valid_file])
        provider.codecommit_client.get_file.side_effect = (
            lambda _repo_name, _path, commit: b"before\n" if commit == "destination-commit" else b"after\n"
        )

        diff_files = provider.get_diff_files()

        assert [diff_file.filename for diff_file in diff_files] == ["good.py"]
        assert provider.codecommit_client.get_file.call_args_list == [
            call("my_test_repo", "good.py", "destination-commit"),
            call("my_test_repo", "good.py", "source-commit"),
        ]

    def test_get_diff_files_does_not_swallow_client_errors(self):
        file = CodeCommitFile("file.py", "before-id", "file.py", "after-id", EDIT_TYPE.MODIFIED)
        provider = self._make_diff_provider([file])
        provider.codecommit_client.get_file.side_effect = ValueError("AWS request failed")

        with pytest.raises(ValueError, match="AWS request failed"):
            provider.get_diff_files()

    def test_get_files_includes_differences_from_every_pull_request_target(self):
        provider = object.__new__(CodeCommitProvider)
        provider.repo_name = "source-repository"
        provider.pr_num = 321
        provider.diff_files = None
        provider.git_files = None
        provider.codecommit_client = MagicMock()

        first_target = MagicMock(
            repository_name="source-repository",
            source_commit="source-commit-1",
            source_branch="feature/one",
            destination_commit="destination-commit-1",
            destination_branch="main",
        )
        second_target = MagicMock(
            repository_name="destination-repository",
            source_commit="source-commit-2",
            source_branch="feature/two",
            destination_commit="destination-commit-2",
            destination_branch="release",
        )
        provider.codecommit_client.get_pr.return_value = MagicMock(
            title="Multi-target PR",
            description="Review both targets",
            targets=[first_target, second_target],
        )
        provider.codecommit_client.get_differences.side_effect = [
            [MagicMock(before_blob_path="one.py", before_blob_id="before-1",
                       after_blob_path="one.py", after_blob_id="after-1", change_type="M")],
            [MagicMock(before_blob_path="two.py", before_blob_id="before-2",
                       after_blob_path="two.py", after_blob_id="after-2", change_type="M")],
        ]

        provider.pr = provider._get_pr()
        files = provider.get_files()

        assert [target.repository_name for target in provider.pr.targets] == [
            "source-repository", "destination-repository"
        ]
        assert [file.filename for file in files] == ["one.py", "two.py"]
        assert [(file.repository_name, file.destination_commit, file.source_commit) for file in files] == [
            ("source-repository", "destination-commit-1", "source-commit-1"),
            ("destination-repository", "destination-commit-2", "source-commit-2"),
        ]
        assert provider.codecommit_client.get_differences.call_args_list == [
            call("source-repository", "destination-commit-1", "source-commit-1"),
            call("destination-repository", "destination-commit-2", "source-commit-2"),
        ]

        provider.codecommit_client.get_file.side_effect = (
            lambda repository, path, commit: {
                ("source-repository", "one.py", "destination-commit-1"): b"before one\n",
                ("source-repository", "one.py", "source-commit-1"): b"after one\n",
                ("destination-repository", "two.py", "destination-commit-2"): b"before two\n",
                ("destination-repository", "two.py", "source-commit-2"): b"after two\n",
            }[(repository, path, commit)]
        )
        diff_files = provider.get_diff_files()

        assert [(file.filename, file.base_file, file.head_file) for file in diff_files] == [
            ("one.py", "before one\n", "after one\n"),
            ("two.py", "before two\n", "after two\n"),
        ]

    def test_publish_comment_uses_every_pull_request_target(self):
        provider = object.__new__(CodeCommitProvider)
        provider.repo_name = "source-repository"
        provider.pr_num = 321
        provider.codecommit_client = MagicMock()
        provider.pr = PullRequestCCMimic(
            "Multi-target PR",
            [],
            targets=[
                MagicMock(
                    repository_name="source-repository",
                    source_commit="source-commit-1",
                    destination_commit="destination-commit-1",
                ),
                MagicMock(
                    repository_name="destination-repository",
                    source_commit="source-commit-2",
                    destination_commit="destination-commit-2",
                ),
            ],
        )

        provider.publish_comment("Review\ncomment")

        assert provider.codecommit_client.publish_comment.call_args_list == [
            call(
                repo_name="source-repository",
                pr_number=321,
                destination_commit="destination-commit-1",
                source_commit="source-commit-1",
                comment="Review\n\ncomment",
            ),
            call(
                repo_name="destination-repository",
                pr_number=321,
                destination_commit="destination-commit-2",
                source_commit="source-commit-2",
                comment="Review\n\ncomment",
            ),
        ]

    def test_persistent_review_creates_then_updates_each_pull_request_target(self):
        targets = [
            SimpleNamespace(
                repository_name="source-repository",
                source_commit="source-commit-1",
                source_branch="refs/heads/feature",
                destination_commit="destination-commit-1",
                destination_branch="refs/heads/main",
            ),
            SimpleNamespace(
                repository_name="source-repository",
                source_commit="source-commit-2",
                source_branch="refs/heads/feature",
                destination_commit="destination-commit-2",
                destination_branch="refs/heads/release",
            ),
        ]
        provider = self._make_persistent_provider(targets=targets)
        provider.codecommit_client.get_comments_for_pull_request.return_value = []

        def publish_comment(**kwargs):
            return {
                "comment": self._comment(
                    kwargs["comment"],
                    comment_id=f"comment-{kwargs['source_commit']}",
                )
            }

        provider.codecommit_client.publish_comment.side_effect = publish_comment
        provider.codecommit_client.update_comment.side_effect = self._successful_update_response
        header = "## Team Review"

        created = provider.publish_persistent_comment(
            f"{header}\n\nfirst review",
            initial_header=header,
            final_update_message=False,
            identity_marker=PRReviewIdentity.REGULAR.value,
            legacy_initial_header=f"{PRReviewHeader.REGULAR.value} 🔍",
        )
        first_bodies = {
            call.kwargs["source_commit"]: call.kwargs["comment"]
            for call in provider.codecommit_client.publish_comment.call_args_list
        }
        provider.codecommit_client.get_comments_for_pull_request.return_value = [
            self._comment_group(
                self._comment(first_bodies["source-commit-1"], comment_id="comment-source-commit-1"),
                before_commit_id="destination-commit-1",
                after_commit_id="source-commit-1",
            ),
            self._comment_group(
                self._comment(first_bodies["source-commit-2"], comment_id="comment-source-commit-2"),
                before_commit_id="destination-commit-2",
                after_commit_id="source-commit-2",
            ),
        ]
        provider.codecommit_client.publish_comment.reset_mock()

        updated = provider.publish_persistent_comment(
            f"{header}\n\nsecond review",
            initial_header=header,
            final_update_message=False,
            identity_marker=PRReviewIdentity.REGULAR.value,
            legacy_initial_header=f"{PRReviewHeader.REGULAR.value} 🔍",
        )

        assert [comment.id for comment in created] == ["comment-source-commit-1", "comment-source-commit-2"]
        assert [comment.id for comment in updated] == ["comment-source-commit-1", "comment-source-commit-2"]
        provider.codecommit_client.publish_comment.assert_not_called()
        assert provider.codecommit_client.update_comment.call_count == 2
        update_bodies = {
            call.args[0]: call.args[1]
            for call in provider.codecommit_client.update_comment.call_args_list
        }
        assert set(update_bodies) == {"comment-source-commit-1", "comment-source-commit-2"}
        assert PRReviewIdentity.REGULAR.value in first_bodies["source-commit-1"]
        assert PRReviewIdentity.REGULAR.value in update_bodies["comment-source-commit-1"]
        assert PRReviewIdentity.REGULAR.value in update_bodies["comment-source-commit-2"]
        assert "second review" in update_bodies["comment-source-commit-1"]
        assert "Review updated until commit source-commit-1" in update_bodies["comment-source-commit-1"]
        assert "Review updated until commit source-commit-2" in update_bodies["comment-source-commit-2"]

    def test_persistent_review_updates_comment_from_older_commit_pair_for_single_target(self):
        provider = self._make_persistent_provider()
        existing_body = f"## Team Review\n\n{PRReviewIdentity.REGULAR.value}\n\nprevious review"
        provider.codecommit_client.get_comments_for_pull_request.return_value = [
            self._comment_group(
                self._comment(existing_body, comment_id="older-commit-comment"),
                before_commit_id="older-destination-commit",
                after_commit_id="older-source-commit",
            )
        ]
        provider.codecommit_client.update_comment.side_effect = self._successful_update_response

        result = provider.publish_persistent_comment(
            "## Team Review\n\nnew review",
            initial_header="## Team Review",
            final_update_message=False,
            identity_marker=PRReviewIdentity.REGULAR.value,
            legacy_initial_header=f"{PRReviewHeader.REGULAR.value} 🔍",
        )

        assert result.id == "older-commit-comment"
        provider.codecommit_client.publish_comment.assert_not_called()
        comment_id, updated_body = provider.codecommit_client.update_comment.call_args.args
        assert comment_id == "older-commit-comment"
        assert "Review updated until commit source-commit-1" in updated_body

    def test_persistent_review_falls_back_to_new_comment_when_comment_listing_fails(self):
        provider = self._make_persistent_provider()
        provider.codecommit_client.get_comments_for_pull_request.side_effect = ValueError("AccessDenied")
        provider.codecommit_client.publish_comment.return_value = {
            "comment": self._comment("created body", comment_id="fallback-comment")
        }

        result = provider.publish_persistent_comment(
            "## Team Review\n\nnew review",
            initial_header="## Team Review",
            final_update_message=False,
            identity_marker=PRReviewIdentity.REGULAR.value,
            legacy_initial_header=f"{PRReviewHeader.REGULAR.value} 🔍",
        )

        assert result.id == "fallback-comment"
        provider.codecommit_client.update_comment.assert_not_called()
        provider.codecommit_client.publish_comment.assert_called_once()
        assert PRReviewIdentity.REGULAR.value in provider.codecommit_client.publish_comment.call_args.kwargs["comment"]

    def test_persistent_review_does_not_use_repository_only_match_for_multiple_targets(self):
        targets = [
            SimpleNamespace(
                repository_name="source-repository",
                source_commit="source-commit-1",
                source_branch="refs/heads/feature",
                destination_commit="destination-commit-1",
                destination_branch="refs/heads/main",
            ),
            SimpleNamespace(
                repository_name="source-repository",
                source_commit="source-commit-2",
                source_branch="refs/heads/feature",
                destination_commit="destination-commit-2",
                destination_branch="refs/heads/release",
            ),
        ]
        provider = self._make_persistent_provider(targets=targets)
        existing_body = f"## Team Review\n\n{PRReviewIdentity.REGULAR.value}\n\nprevious review"
        provider.codecommit_client.get_comments_for_pull_request.return_value = [
            self._comment_group(
                self._comment(existing_body, comment_id="unmatched-comment"),
                before_commit_id="older-destination-commit",
                after_commit_id="older-source-commit",
            )
        ]

        provider.publish_persistent_comment(
            "## Team Review\n\nnew review",
            initial_header="## Team Review",
            final_update_message=False,
            identity_marker=PRReviewIdentity.REGULAR.value,
            legacy_initial_header=f"{PRReviewHeader.REGULAR.value} 🔍",
        )

        provider.codecommit_client.update_comment.assert_not_called()
        assert provider.codecommit_client.publish_comment.call_args_list == [
            call(
                repo_name="source-repository",
                pr_number=321,
                destination_commit="destination-commit-1",
                source_commit="source-commit-1",
                comment=provider.codecommit_client.publish_comment.call_args_list[0].kwargs["comment"],
            ),
            call(
                repo_name="source-repository",
                pr_number=321,
                destination_commit="destination-commit-2",
                source_commit="source-commit-2",
                comment=provider.codecommit_client.publish_comment.call_args_list[1].kwargs["comment"],
            ),
        ]

    def test_persistent_review_does_not_use_ambiguous_destination_match_for_multiple_targets(self):
        targets = [
            SimpleNamespace(
                repository_name="source-repository",
                source_commit="source-commit-a-new",
                source_branch="refs/heads/feature-a",
                destination_commit="shared-destination-commit",
                destination_branch="refs/heads/main",
            ),
            SimpleNamespace(
                repository_name="source-repository",
                source_commit="source-commit-b-new",
                source_branch="refs/heads/feature-b",
                destination_commit="shared-destination-commit",
                destination_branch="refs/heads/main",
            ),
        ]
        provider = self._make_persistent_provider(targets=targets)
        existing_body = f"## Team Review\n\n{PRReviewIdentity.REGULAR.value}\n\nprevious review"
        provider.codecommit_client.get_comments_for_pull_request.return_value = [
            self._comment_group(
                self._comment(
                    existing_body,
                    comment_id="target-b-old",
                    created_at=datetime(2024, 1, 2, tzinfo=timezone.utc),
                ),
                before_commit_id="shared-destination-commit",
                after_commit_id="source-commit-b-old",
            ),
            self._comment_group(
                self._comment(
                    existing_body,
                    comment_id="target-a-old",
                    created_at=datetime(2024, 1, 1, tzinfo=timezone.utc),
                ),
                before_commit_id="shared-destination-commit",
                after_commit_id="source-commit-a-old",
            ),
        ]

        provider.publish_persistent_comment(
            "## Team Review\n\nnew review",
            initial_header="## Team Review",
            final_update_message=False,
            identity_marker=PRReviewIdentity.REGULAR.value,
            legacy_initial_header=f"{PRReviewHeader.REGULAR.value} 🔍",
        )

        provider.codecommit_client.update_comment.assert_not_called()
        assert [
            call.kwargs["source_commit"]
            for call in provider.codecommit_client.publish_comment.call_args_list
        ] == ["source-commit-a-new", "source-commit-b-new"]

    @pytest.mark.parametrize("raw_order", [("old", "new"), ("new", "old")])
    def test_get_issue_comments_uses_oldest_first_creation_order_for_answer(self, raw_order):
        provider = self._make_persistent_provider()
        comments_by_name = {
            "old": self._comment(
                "older answer",
                comment_id="old-comment",
                created_at=datetime(2024, 1, 1, tzinfo=timezone.utc),
                last_modified_at=datetime(2024, 1, 10, tzinfo=timezone.utc),
            ),
            "new": self._comment(
                "newer answer",
                comment_id="new-comment",
                created_at=datetime(2024, 1, 2, tzinfo=timezone.utc),
            ),
        }
        provider.codecommit_client.get_comments_for_pull_request.return_value = [
            self._comment_group(*(comments_by_name[name] for name in raw_order))
        ]

        comments = provider.get_issue_comments()

        assert provider.is_supported("get_issue_comments") is True
        assert provider.supports_review_comment_identity() is True
        assert [comment.id for comment in comments] == ["old-comment", "new-comment"]
        assert comments[0].user.login == "arn:aws:iam::123456789012:user/pr-agent"
        provider.codecommit_client.get_comments_for_pull_request.assert_called_once_with(321)

    @pytest.mark.parametrize("raw_order", [("q-old", "a-old", "q-new", "a-new"), ("a-new", "q-new", "a-old", "q-old")])
    def test_answer_mode_uses_newest_question_and_answer_after_oldest_first_sort(self, raw_order):
        provider = self._make_persistent_provider()
        bodies_by_name = {
            "q-old": "Questions to better understand the PR:\n\nold question",
            "a-old": "/answer old answer",
            "q-new": "Questions to better understand the PR:\n\nnew question",
            "a-new": "/answer new answer",
        }
        dates_by_name = {
            "q-old": datetime(2024, 1, 1, tzinfo=timezone.utc),
            "a-old": datetime(2024, 1, 2, tzinfo=timezone.utc),
            "q-new": datetime(2024, 1, 3, tzinfo=timezone.utc),
            "a-new": datetime(2024, 1, 4, tzinfo=timezone.utc),
        }
        provider.codecommit_client.get_comments_for_pull_request.return_value = [
            self._comment_group(
                *(
                    self._comment(
                        bodies_by_name[name],
                        comment_id=name,
                        created_at=dates_by_name[name],
                    )
                    for name in raw_order
                )
            )
        ]
        reviewer = PRReviewer.__new__(PRReviewer)
        reviewer.is_answer = True
        reviewer.git_provider = provider

        question, answer = reviewer._get_user_answers()

        assert question == bodies_by_name["q-new"]
        assert answer == bodies_by_name["a-new"]

    @pytest.mark.parametrize("raw_order", [("old", "new"), ("new", "old")])
    def test_persistent_review_updates_newest_duplicate_under_both_api_feed_orders(self, raw_order):
        provider = self._make_persistent_provider()
        provider.codecommit_client.update_comment.side_effect = self._successful_update_response
        body = f"## Team Review\n\n{PRReviewIdentity.REGULAR.value}\n\nprevious review"
        comments_by_name = {
            "old": self._comment(
                body,
                comment_id="old-comment",
                created_at=datetime(2024, 1, 1, tzinfo=timezone.utc),
                last_modified_at=datetime(2024, 1, 10, tzinfo=timezone.utc),
            ),
            "new": self._comment(
                body,
                comment_id="new-comment",
                created_at=datetime(2024, 1, 2, tzinfo=timezone.utc),
            ),
        }
        provider.codecommit_client.get_comments_for_pull_request.return_value = [
            self._comment_group(*(comments_by_name[name] for name in raw_order))
        ]

        provider.publish_persistent_comment(
            "## Team Review\n\nnew review",
            initial_header="## Team Review",
            final_update_message=False,
            identity_marker=PRReviewIdentity.REGULAR.value,
            legacy_initial_header=f"{PRReviewHeader.REGULAR.value} 🔍",
        )

        provider.codecommit_client.update_comment.assert_called_once()
        assert provider.codecommit_client.update_comment.call_args.args[0] == "new-comment"
        provider.codecommit_client.publish_comment.assert_not_called()

    def test_get_issue_comments_filters_deleted_replies_inline_and_malformed_comments(self):
        provider = self._make_persistent_provider()
        provider.codecommit_client.get_comments_for_pull_request.return_value = [
            "not a group",
            self._comment_group(self._comment("valid old", comment_id="valid-old")),
            self._comment_group(
                self._comment("reply", comment_id="reply", inReplyTo="valid-old"),
                self._comment("deleted", comment_id="deleted", deleted=True),
                self._comment("missing id", commentId=None),
                self._comment("", comment_id="empty-body"),
                self._comment("bad timestamp", comment_id="bad-timestamp", creationDate="yesterday"),
            ),
            self._comment_group(
                self._comment("inline", comment_id="inline"),
                location={"filePath": "src/app.py", "filePosition": 7},
            ),
            self._comment_group(
                self._comment(
                    "valid new",
                    comment_id="valid-new",
                    created_at=datetime(2024, 1, 2, tzinfo=timezone.utc),
                )
            ),
        ]

        comments = provider.get_issue_comments()

        assert [(comment.id, comment.body) for comment in comments] == [
            ("valid-old", "valid old"),
            ("valid-new", "valid new"),
        ]

    def test_persistent_review_migrates_legacy_heading_to_stable_identity(self):
        provider = self._make_persistent_provider()
        legacy_body = f"{PRReviewHeader.REGULAR.value} 🔍\n\nprevious review"
        provider.codecommit_client.get_comments_for_pull_request.return_value = [
            self._comment_group(self._comment(legacy_body, comment_id="legacy-comment"))
        ]
        provider.codecommit_client.update_comment.side_effect = self._successful_update_response

        provider.publish_persistent_comment(
            "## Custom Review\n\nnew review",
            initial_header="## Custom Review",
            final_update_message=False,
            identity_marker=PRReviewIdentity.REGULAR.value,
            legacy_initial_header=f"{PRReviewHeader.REGULAR.value} 🔍",
        )

        provider.codecommit_client.publish_comment.assert_not_called()
        comment_id, updated_body = provider.codecommit_client.update_comment.call_args.args
        assert comment_id == "legacy-comment"
        assert updated_body.startswith("## Custom Review\n\n")
        assert PRReviewIdentity.REGULAR.value in updated_body

    def test_persistent_review_falls_back_to_new_comment_only_for_failed_target_update(self):
        targets = [
            SimpleNamespace(
                repository_name="source-repository",
                source_commit="source-commit-1",
                source_branch="refs/heads/feature",
                destination_commit="destination-commit-1",
                destination_branch="refs/heads/main",
            ),
            SimpleNamespace(
                repository_name="source-repository",
                source_commit="source-commit-2",
                source_branch="refs/heads/feature",
                destination_commit="destination-commit-2",
                destination_branch="refs/heads/release",
            ),
        ]
        provider = self._make_persistent_provider(targets=targets)
        existing_body = f"## Team Review\n\n{PRReviewIdentity.REGULAR.value}\n\nprevious review"
        provider.codecommit_client.get_comments_for_pull_request.return_value = [
            self._comment_group(
                self._comment(existing_body, comment_id="comment-target-1"),
                before_commit_id="destination-commit-1",
                after_commit_id="source-commit-1",
            ),
            self._comment_group(
                self._comment(existing_body, comment_id="comment-target-2"),
                before_commit_id="destination-commit-2",
                after_commit_id="source-commit-2",
            ),
        ]

        def update_comment(comment_id, body):
            if comment_id == "comment-target-2":
                return {"comment": {"commentId": comment_id, "content": "unexpected body", "deleted": False}}
            return self._successful_update_response(comment_id, body)

        provider.codecommit_client.update_comment.side_effect = update_comment
        provider.codecommit_client.publish_comment.return_value = {
            "comment": self._comment("fallback body", comment_id="fallback-comment")
        }

        result = provider.publish_persistent_comment(
            "## Team Review\n\nnew review",
            initial_header="## Team Review",
            final_update_message=False,
            identity_marker=PRReviewIdentity.REGULAR.value,
            legacy_initial_header=f"{PRReviewHeader.REGULAR.value} 🔍",
        )

        assert [comment.id for comment in result] == ["comment-target-1", "fallback-comment"]
        assert provider.codecommit_client.update_comment.call_count == 2
        provider.codecommit_client.publish_comment.assert_called_once()
        assert provider.codecommit_client.publish_comment.call_args.kwargs["repo_name"] == "source-repository"
        assert provider.codecommit_client.publish_comment.call_args.kwargs["destination_commit"] == "destination-commit-2"
        assert provider.codecommit_client.publish_comment.call_args.kwargs["source_commit"] == "source-commit-2"

    def test_unmarked_persistent_comment_remains_create_only(self):
        provider = self._make_persistent_provider()
        provider.codecommit_client.get_comments_for_pull_request.return_value = [
            self._comment_group(self._comment("## Title\n\nold description", comment_id="describe-comment"))
        ]
        provider.codecommit_client.publish_comment.return_value = {
            "comment": self._comment("## Title\n\nnew description", comment_id="new-describe-comment")
        }

        result = provider.publish_persistent_comment(
            "## Title\n\nnew description",
            initial_header="## Title",
            update_header=True,
            name="describe",
            final_update_message=False,
        )

        assert result.id == "new-describe-comment"
        provider.codecommit_client.get_comments_for_pull_request.assert_not_called()
        provider.codecommit_client.update_comment.assert_not_called()
        provider.codecommit_client.publish_comment.assert_called_once()

    def test_get_issue_comments_support_does_not_enable_gfm_improve_history(self):
        provider = self._make_persistent_provider()

        assert provider.is_supported("get_issue_comments") is True
        assert provider.is_supported("gfm_markdown") is False

    def test_publish_code_suggestion_uses_target_that_contains_file(self):
        provider = object.__new__(CodeCommitProvider)
        provider.repo_name = "source-repository"
        provider.pr_num = 321
        provider.diff_files = None
        provider.codecommit_client = MagicMock()
        provider.pr = PullRequestCCMimic(
            "Multi-target PR",
            [],
            targets=[
                MagicMock(
                    repository_name="source-repository",
                    source_commit="source-commit-1",
                    destination_commit="destination-commit-1",
                ),
                MagicMock(
                    repository_name="destination-repository",
                    source_commit="source-commit-2",
                    destination_commit="destination-commit-2",
                ),
            ],
        )
        provider.git_files = [
            CodeCommitFile(
                "two.py",
                "before-2",
                "two.py",
                "after-2",
                EDIT_TYPE.MODIFIED,
                repository_name="destination-repository",
                source_commit="source-commit-2",
                destination_commit="destination-commit-2",
            )
        ]

        assert provider.publish_code_suggestions([
            {
                "body": "Use a constant",
                "relevant_file": "two.py",
                "relevant_lines_start": 4,
            }
        ]) is True

        provider.codecommit_client.publish_comment.assert_called_once_with(
            repo_name="destination-repository",
            pr_number=321,
            destination_commit="destination-commit-2",
            source_commit="source-commit-2",
            comment="Use a constant",
            annotation_file="two.py",
            annotation_line=4,
        )

    def test_get_title(self):
        # Test that the get_title() function returns the PR title
        with patch.object(CodeCommitProvider, "__init__", lambda x, y: None):
            provider = CodeCommitProvider(None)
            provider.pr = PullRequestCCMimic("My Test PR Title", [])
            assert provider.get_title() == "My Test PR Title"

    def test_get_pr_id(self):
        # Test that the get_pr_id() function returns the correct ID
        with patch.object(CodeCommitProvider, "__init__", lambda x, y: None):
            provider = CodeCommitProvider(None)
            provider.repo_name = "my_test_repo"
            provider.pr_num = 321
            assert provider.get_pr_id() == "my_test_repo/321"

    def test_parse_pr_url(self):
        # Test that the _parse_pr_url() function can extract the repo name and PR number from a CodeCommit URL
        url = "https://us-east-1.console.aws.amazon.com/codesuite/codecommit/repositories/my_test_repo/pull-requests/321"
        repo_name, pr_number = CodeCommitProvider._parse_pr_url(url)
        assert repo_name == "my_test_repo"
        assert pr_number == 321

    def test_is_valid_codecommit_hostname(self):
        # Test the various AWS regions
        assert CodeCommitProvider._is_valid_codecommit_hostname("af-south-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("ap-east-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("ap-northeast-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("ap-northeast-2.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("ap-northeast-3.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("ap-south-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("ap-south-2.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("ap-southeast-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("ap-southeast-2.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("ap-southeast-3.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("ap-southeast-4.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("ca-central-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("eu-central-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("eu-central-2.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("eu-north-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("eu-south-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("eu-south-2.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("eu-west-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("eu-west-2.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("eu-west-3.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("il-central-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("me-central-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("me-south-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("sa-east-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("us-east-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("us-east-2.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("us-gov-east-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("us-gov-west-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("us-west-1.console.aws.amazon.com")
        assert CodeCommitProvider._is_valid_codecommit_hostname("us-west-2.console.aws.amazon.com")
        # Test non-AWS regions
        assert not CodeCommitProvider._is_valid_codecommit_hostname("no-such-region.console.aws.amazon.com")
        assert not CodeCommitProvider._is_valid_codecommit_hostname("console.aws.amazon.com")

    # Test that an error is raised when an invalid CodeCommit URL is provided to the set_pr() method of the CodeCommitProvider class.
    # Generated by CodiumAI
    def test_invalid_codecommit_url(self):
        provider = CodeCommitProvider()
        with pytest.raises(ValueError):
            provider.set_pr("https://example.com/codecommit/repositories/my_test_repo/pull-requests/4321")

    def test_get_file_extensions(self):
        filenames = [
            "app.py",
            "cli.py",
            "composer.json",
            "composer.lock",
            "hello.py",
            "image1.jpg",
            "image2.JPG",
            "index.js",
            "provider.py",
            "README",
            "test.py",
        ]
        expected_extensions = [
            ".py",
            ".py",
            ".json",
            ".lock",
            ".py",
            ".jpg",
            ".jpg",
            ".js",
            ".py",
            "",
            ".py",
        ]
        extensions = CodeCommitProvider._get_file_extensions(filenames)
        assert extensions == expected_extensions

    def test_get_language_percentages(self):
        extensions = [
            ".py",
            ".py",
            ".json",
            ".lock",
            ".py",
            ".jpg",
            ".jpg",
            ".js",
            ".py",
            "",
            ".py",
        ]
        percentages = CodeCommitProvider._get_language_percentages(extensions)
        assert percentages[".py"] == 45
        assert percentages[".json"] == 9
        assert percentages[".lock"] == 9
        assert percentages[".jpg"] == 18
        assert percentages[".js"] == 9
        assert percentages[""] == 9

        # The _get_file_extensions function needs the "." prefix on the extension,
        # but the _get_language_percentages function will work with or without the "." prefix
        extensions = [
            "txt",
            "py",
            "py",
        ]
        percentages = CodeCommitProvider._get_language_percentages(extensions)
        assert percentages["py"] == 67
        assert percentages["txt"] == 33

        # test an empty list
        percentages = CodeCommitProvider._get_language_percentages([])
        assert percentages == {}

    def test_get_edit_type(self):
        # Test that the _get_edit_type() function can convert a CodeCommit letter to an EDIT_TYPE enum
        assert CodeCommitProvider._get_edit_type("A") == EDIT_TYPE.ADDED
        assert CodeCommitProvider._get_edit_type("D") == EDIT_TYPE.DELETED
        assert CodeCommitProvider._get_edit_type("M") == EDIT_TYPE.MODIFIED
        assert CodeCommitProvider._get_edit_type("R") == EDIT_TYPE.RENAMED

        assert CodeCommitProvider._get_edit_type("a") == EDIT_TYPE.ADDED
        assert CodeCommitProvider._get_edit_type("d") == EDIT_TYPE.DELETED
        assert CodeCommitProvider._get_edit_type("m") == EDIT_TYPE.MODIFIED
        assert CodeCommitProvider._get_edit_type("r") == EDIT_TYPE.RENAMED

        assert CodeCommitProvider._get_edit_type("X") is None

    def test_add_additional_newlines(self):
        # a short string to test adding double newlines
        input = "abc\ndef\n\n___\nghi\njkl\nmno\n\npqr\n"
        expect = "abc\n\ndef\n\n___\n\nghi\n\njkl\n\nmno\n\npqr\n\n"
        assert CodeCommitProvider._add_additional_newlines(input) == expect
        # a test example from a real PR
        input = "## PR Type:\nEnhancement\n\n___\n## PR Description:\nThis PR introduces a new feature to the script, allowing users to filter servers by name.\n\n___\n## PR Main Files Walkthrough:\n`foo`: The foo script has been updated to include a new command line option `-f` or `--filter`.\n`bar`: The bar script has been updated to list stopped servers.\n"
        expect = "## PR Type:\n\nEnhancement\n\n___\n\n## PR Description:\n\nThis PR introduces a new feature to the script, allowing users to filter servers by name.\n\n___\n\n## PR Main Files Walkthrough:\n\n`foo`: The foo script has been updated to include a new command line option `-f` or `--filter`.\n\n`bar`: The bar script has been updated to list stopped servers.\n\n"
        assert CodeCommitProvider._add_additional_newlines(input) == expect

    def test_remove_markdown_html(self):
        input = "## PR Feedback\n<details><summary>Code feedback:</summary>\nfile foo\n</summary>\n"
        expect = "## PR Feedback\nCode feedback:\nfile foo\n\n"
        assert CodeCommitProvider._remove_markdown_html(input) == expect
